title: Datarmor documentation
author:
  - name: Nicolas Barrier
    orcid: 0000-0002-1693-4719
    email:  nicolas.barrier@ird.fr
    affiliations:
      - name: IRD

format:
  revealjs:
    smaller: true
    theme: [default, custom.scss]
    output-file: slides_datarmor-documentation.html
  pdf:
    toc: false
    number-sections: false
    colorlinks: true
    linestretch: 1.5
    fontsize: 13pt
    output-file: datarmor-documentation.pdf
